<?php
// $Id$
/**
* Implementation of hook_views_api().
*/
function apachesolr_passthru_views_api() {
  return array('api' => '3');
}

/**
 * Implementation of hook_apachesolr_modify_query.
 */
function apachesolr_passthru_apachesolr_modify_query(&$query, &$params, $caller) {
  if ($caller == 'apachesolr_search') {
    $params['fl'] .= ',company_name,cro_number,line_of_business,postcode,telephone_number,uk_sic_03';
  }
}

/**
 * Implementation of hook_apachesolr_finalize_query.
 */
function apachesolr_views_query_finalize_query(&$query, &$params) {
dargs();
  $params['q'] = '';
}

function apachesolr_passthru_apachesolr_search_result_alter(&$doc) {
  $doc->path = 'company/' . $doc->cro_number;
  $doc->title = $doc->company_name;
  $doc->body = $doc->postcode . ' - ' . $doc->uk_sic_03 . ' - ' . $doc->line_of_business;
  return $doc;
}


/**
 * Implementation of hook_apachesolr_facets().
 *
 * Returns an array keyed by block delta.
 */
function apachesolr_passthru_apachesolr_facets() {
  $facets = array();

  $facets['type'] = array(
    'info' => t('Apache Solr Passthru: Filter by SIC(03)'),
    'facet_field' => 'uk_sic_03',
  );
  return $facets;
}


/**
 * Implementation of hook_block().
 */
function apachesolr_passthru_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $enabled_facets = apachesolr_get_enabled_facets('apachesolr_passthru');
      $facets = apachesolr_passthru_apachesolr_facets();
      // Add the blocks
      $blocks = array();
      foreach ($enabled_facets as $delta => $facet_field) {
        if (isset($facets[$delta])) {
          $blocks[$delta] = $facets[$delta] + array('cache' => BLOCK_CACHE_PER_PAGE);
        }
      }
      return $blocks;

    case 'view':
      if (apachesolr_has_searched()) {
        // Get the query and response. Without these no blocks make sense.
        $response = apachesolr_static_response_cache();
        if (empty($response)) {
          return;
        }
        $query = apachesolr_current_query();

        $enabled_facets = apachesolr_get_enabled_facets('apachesolr_passthru');
        $key = $enabled_facets[$delta];
        if (empty($key)) {
          return;
        }

        $facet = $response->facet_counts->facet_fields->{$key};
        if (is_object($facet)) {
          $facets = array();

          foreach($facet as $facet_field => $count) {
            if ($facet_field != '_empty_') {
              $active = $query->has_filter($key, $facet_field);
              $facets[$facet_field] = array(
                '#name' => $key,
                '#value' => $facet_field,
                '#exclude' => FALSE,
                '#count' => $count,
                '#parent' => 0,
                '#children' => array(),
                '#has_children' => false,
                '#active' => $active,
              );
            }
          }

          $items = apachesolr_search_nested_facet_items($query, $facets, $response->response->numFound);
          if ($items && ($response->response->numFound > 0)) {
            $limit = isset($initial_limits['apachesolr_passthru'][$key]) ? $initial_limits['apachesolr_passthru'][$key] : $limit_default;
            return array(
              'subject' => t('Filter by SIC(03)'),
              'content' => theme('apachesolr_facet_list', $items, $limit),
            );
          }
        }
      }
      break;

    case 'configure':
      return apachesolr_facetcount_form('apachesolr_passthru', $delta);
      break;

    case 'save':
      apachesolr_facetcount_save($edit);
      break;
  }
}
